### ISSUE TITLE
downloadable version of the package

### ISSUE THREAD

**Issue by yegor256** [fewbytes-cookbooks/artifactory#4]
Would be great if you create a downloadable release of the package.

**Comment by nukemberg** [comment]
Are you referring to a packaged version of the cookbook? e.g. containing all dependency cookbooks? if so, you can easily generate one using berkshelf.

**Comment by yegor256** [comment]
Yes, agree, but would be convenient to have it packaged by you, like it's done in other cookbooks provided by opcode

**Comment by nukemberg** [comment]
hmm. can you give a reference for me to look at?

**Comment by yegor256** [comment]
https://github.com/opscode-cookbooks/jenkins/releases

**Comment by nukemberg** [comment]
This is just a tarball of the tagged commit. it contains no dependencies or whatever. if you want such a package simply click on "download as a zip" on the github repo page.

**Comment by yegor256** [comment]
Yes, I already did :) But I'm suggesting you to the same as opcode is doing with their cookbooks. Just suggesting :)

**Comment by nukemberg** [comment]
opscode use tags because their cookbooks are under active development and versions change frequently. this cookbook is only updated if/when bugs are found - i've received few pull requests and my artifactory installations are too rare to provoke additional features. i will use release tags when there is something to release.
